name: otel-grpc-demo

services:

  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.1
    ports:
      - "18888:18888"
      - "4317:18889"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"


  prometheus:
    image: prom/prometheus:v3.2.1
    ports:
      - '9090:9090'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command:
      - '--enable-feature=exemplar-storage'
      - '--enable-feature=native-histograms'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--storage.tsdb.retention.size=16GB'
      - '--web.enable-otlp-receiver'
    volumes:
      - ./prometheus-provisioning/prometheus.yaml:/etc/prometheus/prometheus.yml
